production:
  database: mysql://wxj:t5*m3$A@localhost/wxj 
  base_uri: http://holt.mrl.nott.ac.uk/
  ga_id: 1
  socket_io_url: 0.0.0.0
  socket_io_port: 49991
development:
  database: mysql://jtruck:jtruck@localhost/jtruck_db 
  base_uri: http://holt.mrl.nott.ac.uk/
  ga_id: 1
  socket_io_url: 0.0.0.0
  socket_io_port: 49991
